# Generated by Django 3.2.9 on 2021-11-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dsecription',
            new_name='description',
        ),
    ]
